name: Component tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

  schedule:
    - cron: 0 0 * * MON

jobs:
  build:
    name: 'Build worker'
    uses: ./.github/workflows/build.yml
    with:
      deploy-artifacts: true

  build-test-tools:
    name: 'Build test tools'
    uses: ./.github/workflows/build-test-tools.yml

  test:
    name: 'Run tests'
    needs: [build, build-test-tools]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install gcc
        run: |
          sudo apt update
          sudo apt install gcc-11 g++-11
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential autoconf libtool pkg-config libomp-dev libprotobuf-dev ninja-build clang-15 libclang-15-dev
        shell: bash

      - uses: ./proto/action/install-grpc
        with:
          prefix: ${{github.workspace}}/external/grpc

      - name: Download worker artifact
        uses: actions/download-artifacts@3
        with:
          name: executor-worker
          path: ${{github.workspace}}/worker_home

      - name: Download test utility artifacts
        uses: actions/download-artifacts@3
        with:
          name: test-utils
          path: ${{github.workspace}}/test_home